--!strict

local Remotes = {
	Events = {
		"PlayerDataLoadedEvent",
		"ClientReadyEvent",
		"SurvivalUpdatedEvent",
		"InventoryUpdatedEvent",
		"CampUpdatedEvent",
		"QuestProgressEvent",
		"SetLocaleEvent",
		"LocaleChangedEvent",
		"EquipItemEvent",
		"SetHotbarSlotEvent",
		"UseItemEvent",
		"CraftItemEvent",
		"CraftResultEvent",
		"RecipesUpdatedEvent",
		"PlaceStructureEvent",
		"PlaceStructureResultEvent",
		"DemolishStructureEvent",
		"DemolishStructureResultEvent",
		"MoveStructureEvent",
		"MoveStructureResultEvent",
		"TransferItemEvent",
	},
	Functions = {},
}

return Remotes
